// Mock data for demo/simulation mode when backend is unavailable

export const MOCK_JOBS = [
  {
    id: "mock_job_001",
    title: "Solidity Developer for DeFi Staking Protocol",
    description: "We are building a multi-asset staking protocol on Ethereum. Looking for an experienced Solidity developer to implement reward distribution, lock-up periods, and emergency withdrawal logic. Must include full Foundry test suite.",
    budget: "3500",
    skills: ["Solidity", "DeFi", "Foundry", "ERC-20", "Staking"],
    status: "OPEN",
    deadline: "2026-05-06T00:00:00Z",
    createdAt: "2026-04-12T00:00:00Z",
    client: { walletAddress: "0x742d35cc6634c0532925a3b844bc454e4438f44e" },
    _count: { applications: 3 },
  },
  {
    id: "mock_job_002",
    title: "Frontend Developer — DeFi Dashboard (Next.js + wagmi)",
    description: "Build a clean, responsive dashboard for our DeFi protocol. Users need to see their staked positions, pending rewards, APY, and transaction history. Stack: Next.js 14, wagmi v2, Tailwind CSS. Figma file provided.",
    budget: "2200",
    skills: ["React", "Next.js", "wagmi", "TypeScript", "TailwindCSS", "DeFi"],
    status: "OPEN",
    deadline: "2026-04-29T00:00:00Z",
    createdAt: "2026-04-14T00:00:00Z",
    client: { walletAddress: "0x742d35cc6634c0532925a3b844bc454e4438f44e" },
    _count: { applications: 2 },
  },
  {
    id: "mock_job_003",
    title: "Smart Contract — ERC-721 NFT Collection with Allowlist",
    description: "Need a gas-optimised ERC-721A contract for a 5,000-piece generative NFT drop. Features: Merkle-proof allowlist, public mint, reveal mechanic, royalty (EIP-2981), owner withdrawal. Full Hardhat test suite required.",
    budget: "1800",
    skills: ["Solidity", "NFT", "ERC-721", "Hardhat", "OpenZeppelin"],
    status: "OPEN",
    deadline: "2026-04-25T00:00:00Z",
    createdAt: "2026-04-11T00:00:00Z",
    client: { walletAddress: "0xab5801a7d398351b8be11c439e05c5b3259aec9b" },
    _count: { applications: 3 },
  },
  {
    id: "mock_job_004",
    title: "UI/UX Designer — NFT Marketplace Redesign",
    description: "Our marketplace needs a full visual refresh. Looking for a Web3-savvy designer to create high-fidelity Figma mockups for: landing page, collection page, item detail, wallet connect flow, and profile page.",
    budget: "1400",
    skills: ["UI/UX", "Figma", "Web3 UX", "Design Systems"],
    status: "OPEN",
    deadline: "2026-05-03T00:00:00Z",
    createdAt: "2026-04-13T00:00:00Z",
    client: { walletAddress: "0xab5801a7d398351b8be11c439e05c5b3259aec9b" },
    _count: { applications: 2 },
  },
  {
    id: "mock_job_005",
    title: "Solidity — ERC-4626 Vault with Auto-Compounding",
    description: "Implement an ERC-4626 tokenised vault with auto-compounding strategy. Must integrate with Aave v3 for yield. Full test suite expected (Foundry). Deployment to X Layer testnet included.",
    budget: "3500",
    skills: ["Solidity", "ERC-4626", "Aave", "Foundry", "DeFi"],
    status: "OPEN",
    deadline: "2026-05-30T00:00:00Z",
    createdAt: "2026-04-12T00:00:00Z",
    client: { walletAddress: "0xA1b2C3d4E5f6A7B8c9D0e1F2a3B4c5D6e7F8a9B0" },
    _count: { applications: 2 },
  },
  {
    id: "mock_job_006",
    title: "Token Economics Design & Whitepaper",
    description: "Design token distribution, vesting schedules, staking mechanics, and governance model for our NFT platform token. Deliver a 20-page whitepaper and tokenomics spreadsheet.",
    budget: "1200",
    skills: ["Tokenomics", "Whitepaper", "Game Theory", "Economic Modelling"],
    status: "OPEN",
    deadline: "2026-05-15T00:00:00Z",
    createdAt: "2026-04-13T00:00:00Z",
    client: { walletAddress: "0xB2C3d4E5F6a7b8C9D0E1f2A3B4C5d6E7f8A9b0c1" },
    _count: { applications: 2 },
  },
  {
    id: "mock_job_007",
    title: "React Native Mobile DApp — Play-to-Earn Game Client",
    description: "Full mobile app (iOS + Android) for our P2E game. WalletConnect integration, in-game NFT inventory UI, live match feed via WebSockets. Expo-managed workflow preferred.",
    budget: "4000",
    skills: ["React Native", "Expo", "WalletConnect", "TypeScript", "WebSockets"],
    status: "OPEN",
    deadline: "2026-06-14T00:00:00Z",
    createdAt: "2026-04-14T00:00:00Z",
    client: { walletAddress: "0xC3D4e5F6a7B8c9D0E1F2a3b4C5D6E7f8a9B0c1D2" },
    _count: { applications: 2 },
  },
];

export const MOCK_APPLICATIONS = [
  {
    id: "app_1",
    jobTitle: "Smart Contract Audit",
    freelancer: { walletAddress: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef", displayName: "Dave Okafor" },
    status: "SHORTLISTED",
    coverLetter: "I've audited 40+ DeFi contracts. Specialising in yield vaults and gas optimisation.",
    bid: "3500",
    timestamp: "2026-04-14T10:00:00Z",
  },
  {
    id: "app_2",
    jobTitle: "React Dashboard",
    freelancer: { walletAddress: "0x1234567890123456789012345678901234567890", displayName: "Bob Martinez" },
    status: "HIRED",
    coverLetter: "DeFi dashboards are my bread and butter. Built 3 in the last year using Next.js + wagmi.",
    bid: "2200",
    timestamp: "2026-04-13T14:30:00Z",
  },
  {
    id: "app_3",
    jobTitle: "API Integration",
    freelancer: { walletAddress: "0x5b38da6a701c568545dcfcb03fcb875f56beddc4", displayName: "Elena Vasquez" },
    status: "PENDING",
    coverLetter: "I build backend systems and on-chain data pipelines for Web3 companies.",
    bid: "1200",
    timestamp: "2026-04-12T09:15:00Z",
  },
];

export const MOCK_PROFILES = [
  {
    id: "prof_1",
    walletAddress: "0x1234567890123456789012345678901234567890",
    displayName: "Bob Martinez",
    tagline: "Full-stack Web3 developer · Next.js + Solidity",
    bio: "5 years of full-stack Web3 development. I build end-to-end dApps: React/Next.js frontends, Node.js backends, and Solidity smart contracts.",
    skills: ["React", "Next.js", "Solidity", "TypeScript", "Node.js", "Hardhat"],
    hourlyRate: "120",
    availability: "AVAILABLE" as const,
    rating: 4.7,
    completedProjects: 12,
    totalEarned: "45600",
    portfolioUrl: "https://github.com/0xBobMartinez",
    role: "FREELANCER",
    portfolioItems: [
      { id: "p1", title: "DeFi Lending Protocol", description: "Full-stack lending protocol with React + Solidity.", tags: ["Solidity", "React", "DeFi"], projectUrl: "https://github.com", imageUrl: null },
      { id: "p2", title: "NFT Mint Launchpad", description: "ERC-721 launchpad with allow-list minting.", tags: ["NFT", "Solidity", "Next.js"], projectUrl: "https://github.com", imageUrl: null },
    ],
  },
  {
    id: "prof_2",
    walletAddress: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    displayName: "Carol Nguyen",
    tagline: "UI/UX designer for Web3 — Figma to production",
    bio: "I design beautiful, user-friendly interfaces for Web3 products. From wallet UX flows to DeFi dashboards.",
    skills: ["UI/UX", "Figma", "React", "Tailwind CSS", "Design Systems", "Web3 UX"],
    hourlyRate: "95",
    availability: "BUSY" as const,
    rating: 4.9,
    completedProjects: 8,
    totalEarned: "28000",
    portfolioUrl: "https://dribbble.com/0xCarol",
    role: "FREELANCER",
    portfolioItems: [],
  },
  {
    id: "prof_3",
    walletAddress: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    displayName: "Dave Okafor",
    tagline: "Solidity engineer & DeFi protocol architect",
    bio: "Senior Solidity engineer with 7 years of EVM experience. Audited 40+ contracts. Built production DeFi protocols managing $50M+ TVL.",
    skills: ["Solidity", "Foundry", "DeFi", "ERC-20", "ERC-4626", "Auditing", "OpenZeppelin"],
    hourlyRate: "150",
    availability: "AVAILABLE" as const,
    rating: 5.0,
    completedProjects: 20,
    totalEarned: "112000",
    portfolioUrl: "https://github.com/0xDaveOkafor",
    role: "FREELANCER",
    portfolioItems: [
      { id: "p3", title: "ERC-4626 Yield Vault", description: "Auto-compounding vault integrating with Aave v3. $8M TVL on mainnet.", tags: ["Solidity", "DeFi", "Foundry"], projectUrl: "https://github.com", imageUrl: null },
      { id: "p4", title: "Cross-chain Bridge", description: "LayerZero-powered USDC bridge across Ethereum, Arbitrum, Polygon.", tags: ["Solidity", "LayerZero", "Cross-chain"], projectUrl: "https://github.com", imageUrl: null },
    ],
  },
  {
    id: "prof_4",
    walletAddress: "0x5b38da6a701c568545dcfcb03fcb875f56beddc4",
    displayName: "Elena Vasquez",
    tagline: "Python engineer & blockchain data analyst",
    bio: "I build backend systems and on-chain data pipelines for Web3 companies. Specialities: The Graph subgraphs, event indexing, Python analytics.",
    skills: ["Python", "The Graph", "Node.js", "GraphQL", "PostgreSQL", "Data Engineering"],
    hourlyRate: "110",
    availability: "AVAILABLE" as const,
    rating: 4.6,
    completedProjects: 9,
    totalEarned: "38500",
    portfolioUrl: "https://github.com/0xElenaV",
    role: "FREELANCER",
    portfolioItems: [],
  },
  {
    id: "prof_5",
    walletAddress: "0xD4E5f6A7B8C9d0E1f2A3b4C5d6E7F8a9b0C1d2E3",
    displayName: "Daniel Park",
    tagline: "Senior Solidity engineer & DeFi security specialist",
    bio: "Senior Solidity engineer, 6 yrs exp. Audited 30+ contracts. Specialises in DeFi vaults and gas optimisation.",
    skills: ["Solidity", "Hardhat", "DeFi", "ERC-20", "OpenZeppelin", "Foundry"],
    hourlyRate: "140",
    availability: "AVAILABLE" as const,
    rating: 4.9,
    completedProjects: 18,
    totalEarned: "87200",
    portfolioUrl: "https://github.com/0xDaniel",
    role: "FREELANCER",
    portfolioItems: [],
  },
  {
    id: "prof_6",
    walletAddress: "0xE5F6a7b8C9D0e1F2A3B4c5D6e7F8A9B0C1d2E3f4",
    displayName: "Eve Larsson",
    tagline: "Full-stack Web3 developer · React + wagmi",
    bio: "Full-stack Web3 developer. React + wagmi + Next.js. Open to long-term retainers.",
    skills: ["React", "Next.js", "wagmi", "TypeScript", "TailwindCSS", "ethers.js"],
    hourlyRate: "100",
    availability: "BUSY" as const,
    rating: 4.8,
    completedProjects: 11,
    totalEarned: "52000",
    portfolioUrl: "https://github.com/0xEve",
    role: "FREELANCER",
    portfolioItems: [],
  },
  {
    id: "prof_7",
    walletAddress: "0xF6a7B8C9d0E1f2A3b4C5d6E7F8A9b0c1D2E3f4A5",
    displayName: "Frank Osei",
    tagline: "Backend & subgraph engineer for Web3",
    bio: "Backend engineer specialising in Node.js APIs, subgraphs, and indexers for Web3 apps.",
    skills: ["Node.js", "GraphQL", "The Graph", "PostgreSQL", "Docker", "Redis"],
    hourlyRate: "90",
    availability: "AVAILABLE" as const,
    rating: 4.6,
    completedProjects: 7,
    totalEarned: "29400",
    portfolioUrl: "https://github.com/0xFrank",
    role: "FREELANCER",
    portfolioItems: [],
  },
  {
    id: "prof_8",
    walletAddress: "0xa7B8c9D0E1F2a3B4C5D6e7f8A9b0C1D2e3F4A5b6",
    displayName: "Grace Kim",
    tagline: "Token economist & whitepaper author",
    bio: "Token economist and whitepaper author. Helped design tokenomics for 12 mainnet launches.",
    skills: ["Tokenomics", "Whitepaper", "Game Theory", "Economic Modelling", "Python"],
    hourlyRate: "110",
    availability: "AVAILABLE" as const,
    rating: 4.7,
    completedProjects: 12,
    totalEarned: "41800",
    portfolioUrl: "https://github.com/0xGrace",
    role: "FREELANCER",
    portfolioItems: [],
  },
  {
    id: "prof_9",
    walletAddress: "0xb8C9D0e1F2A3b4c5D6E7F8A9b0C1d2e3F4A5B6c7",
    displayName: "Henry Addo",
    tagline: "React Native & Web3 mobile developer",
    bio: "React Native + Expo developer. Shipped 4 production Web3 mobile apps.",
    skills: ["React Native", "Expo", "iOS", "Android", "WalletConnect", "TypeScript"],
    hourlyRate: "85",
    availability: "AVAILABLE" as const,
    rating: 4.5,
    completedProjects: 4,
    totalEarned: "18500",
    portfolioUrl: "https://github.com/0xHenry",
    role: "FREELANCER",
    portfolioItems: [],
  },
];
